const LOGIN_REQUEST = "LOGINREQUEST";
const LOGIN_SUCCESSFUL = "LOGINSUCCESSFUL";
const LOGIN_UNSUCCESSFULL = "LOGINUNSUCCESSFUL";
const STORE_USERDATA = "STOREUSERDATA";
const STORE_USER_FAILED = "STOREUSERFAILED";
const LOGIN_PROCESS = "LOGINPROCESS";
const CHECK_USER_LOGGEDIN = "CHECK_USER_LOGGEDIN";
const LOGOUT_PROCESS = "LOGOUT";

export {
  LOGIN_REQUEST,
  LOGIN_SUCCESSFUL,
  LOGIN_UNSUCCESSFULL,
  STORE_USERDATA,
  LOGIN_PROCESS,
  STORE_USER_FAILED,
  CHECK_USER_LOGGEDIN,
  LOGOUT_PROCESS,
};
